# Generated by Django 5.1 on 2025-11-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('e', 'Entertainment'), ('m', 'Music'), ('i', 'IT')], default='e', max_length=15),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
